name: Sync Documentation to Notion

on:
  push:
    branches: [main]
    paths: ['docs/**', 'README.md']

jobs:
  sync-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Sync to Notion
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        run: |
          curl -X POST "https://api.notion.com/v1/pages" \
            -H "Authorization: Bearer $NOTION_TOKEN" \
            -H "Notion-Version: 2022-06-28" \
            -H "Content-Type: application/json" \
            -d '{
              "parent": {"page_id": "${{ secrets.NOTION_PAGE_ID }}"},
              "properties": {
                "title": {"title": [{"text": {"content": "Updated Documentation"}}]}
              }
            }'